### ISSUE TITLE
How to create links to specific characters?

### ISSUE THREAD

**Issue by maxdesalle** [aklt/rel.vim#3]
The documentation seems to be unfinished, as the [section explaining character linking isn't written](https://github.com/aklt/rel.vim/blob/5c4737dff14d55bf0c2d7c16ab163278216f71f3/doc/rel.txt#L204). I would love to be able to create links to specific characters using **rel**.

**Comment by aklt** [comment]
Yes, you are right!  I was meaning to implement this, but have been busy with other things.

Thanks for your comment, this could be a good occasion for me to give `rel.vim` some more love :-)

**Comment by aklt** [comment]
Hello @maxdesalle, how would you like this to work?

I am updating this plugin a little, finally.

**Comment by aklt** [comment]
I'll close this issue.  Please open a new one if needed.
